services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: ["8080:8080"]
    env_file: .env.local
    environment:
      - DOCKER_CONTAINER=true
    volumes:
      - .:/app